version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "0000"
      PGPORT: 5438
      POSTGRES_USER : postgres
      POSTGRES_DB : task_management
    ports:
      - 5438:5438
    volumes:
      - vardata:/var/
      - appdata:/usr/src/app
    

  
  app:
    container_name: taskm_app
    build: ./
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  vardata:
  appdata: